version: "2.4"
services:

  node:
    container_name: givemeaport
    image: node:12
    cpus: 0.2
    mem_limit: 100m
    memswap_limit: 200m
    logging:
      options:
        max-size: "100m"
    networks:
      - nginx
    ports:
      - "56865:3000"
    volumes:
      - ./:/GiveMeAPort
    working_dir: /GiveMeAPort
    command: sh -c "npm i && npm start"

networks:
  nginx:
    name: nginx_default
    external: true
